const WISHLIST_VERSION = 5;
const DEFAULT_WISHLIST = {
  s1: [
    { id:"s1-01", name:"엽산", priority:"필수", target:"mom", emoji:"💊", desc:"보건소에서도 줘요! 출산 직후에도 영양소 손실을 방지하기 위해 복용하는게 좋아요." },
    { id:"s1-02", name:"철분", priority:"필수", target:"mom", emoji:"🩸", desc:"보건소에서도 줘요! 임신 빈혈 예방을 위해 꾸준한 섭취가 중요해요. 변비가 생길 수 있으니 물도 함께 챙겨주세요." },
    { id:"s1-03", name:"튼살오일 / 튼살크림", priority:"필수", target:"mom", emoji:"🧴", desc:"배가 나오기 전부터 꾸준히 발라두면 좋아요. 엉덩이와 허벅지에도 바르는 것을 잊지마세요!" },
    { id:"s1-04", name:"임산부 민소매 / 브라 / 팬티", priority:"필수", target:"mom", emoji:"👙", desc:"조이지 않는 속옷을 골라요. 튼살크림을 바르고 배를 덮는 팬티나 민소매를 입으면 오래 촉촉해요." },
    { id:"s1-05", name:"비타민C", priority:"권장", target:"mom", emoji:"🍊", desc:"철분의 흡수를 도와주지만, 과량 섭취는 태아의 비타민C 의존증을 만들수 있어요." },
    { id:"s1-06", name:"비타민D", priority:"권장", target:"mom", emoji:"☀️", desc:"햇빛이 부족하면 중요해요. 지용성 비타민으로 기름기가 있는 음식과 함께 먹으면 흡수가 잘돼요." },
    { id:"s1-07", name:"유산균", priority:"권장", target:"mom", emoji:"🦠", desc:"무균상태인 태아의 장 속에 유익균을 장착하도록 도와줘요. 엄마의 배변 리듬에도 도움이 돼요!" },
    { id:"s1-08", name:"오메가3", priority:"권장", target:"mom", emoji:"🐟", desc:"아기의 시각, 인지 능력 발달을 도와주지만, 임산부의 70% 이상이 부족하다고 해요." },
    { id:"s1-09", name:"칼슘", priority:"권장", target:"mom", emoji:"🥛", desc:"칼슘제 vs. 철분제는 서로의 체내 흡수를 방해하므로 시차를 두세요! 예. 칼아침-철저녁!" },
    { id:"s1-10", name:"샴푸 / 트리트먼트 / 바디워시", priority:"권장", target:"mom", emoji:"🧼", desc:"피부가 예민해질 수 있으니 향이 강하지 않은 순한 성분으로 바꿔주세요!" },
    { id:"s1-11", name:"미세모 칫솔", priority:"권장", target:"mom", emoji:"🪥", desc:"잇몸이 쉽게 붓는 시기에 미세 칫솔모를 사용하여 치주염을 예방해요." },
    { id:"s1-12", name:"저불소 / 무불소 치약", priority:"권장", target:"mom", emoji:"🦷", desc:"여러 번 헹궈도 입안 점막은 피부보다 흡수율이 훨씬 높으니 안전한 치약을 골라보아요!" },
    { id:"s1-13", name:"루이보스티", priority:"선택", target:"mom", emoji:"🍵", desc:"충분한 수분 섭취는 양수와 부종 예방에 도움이 되니 루이보스 아니더라도 Drink!" },
    { id:"s1-14", name:"핸드크림", priority:"선택", target:"mom", emoji:"🤲", desc:"부드러운 핸드크림을 바르고 손마사지를보면 입덧 완화에도 좋아요!" },
    { id:"s1-15", name:"립밤", priority:"선택", target:"mom", emoji:"💋", desc:"입술이 쉽게 마르기도 하니 향이 강하지 않은 립밤을 골라보아요." },
    { id:"s1-16", name:"입덧밴드", priority:"선택", target:"mom", emoji:"⌚", desc:"팔의 정중신경을 자극하여 입덧을 느끼는 뇌의 감각 신호를 줄여주는 효과예요." },
    { id:"s1-17", name:"입덧캔디", priority:"선택", target:"mom", emoji:"🍬", desc:"강한 신맛으로 입덧을 조금 완화할 수 있어요. 너무 심하면 병원가서 약을 먹어요!" },
    { id:"s1-18", name:"육아도서 / 백과", priority:"선택", target:"mombaby", emoji:"📚", desc:"" }
  ],
  s2: [
    { id:"s2-01", name:"임부복 / 레깅스", priority:"필수", target:"mom", emoji:"👗", desc:"배가 커지기 시작하면 꽉 끼지 않는 옷이 편해요. 꼭 임부복이 아니어도, 여유있는 원피스라면 괜찮아요." },
    { id:"s2-02", name:"복대 (산전 복대)", priority:"권장", target:"mom", emoji:"🎗️", desc:"배가 무거워지며 허리가 불편할때 도움이 돼요. 특히 이동이 많은 임산부의 허리 통증에 도움이 돼요." },
    { id:"s2-03", name:"바디필로우", priority:"권장", target:"mom", emoji:"🛏️", desc:"옆으로 누워자는 시간이 많아일때 허리와 배를 편하게 해줘요. 내장재와 쿠션감이 좋은 제품을 고르세요." },
    { id:"s2-04", name:"미끄럼방지용품", priority:"권장", target:"baby", emoji:"🦶", desc:"몸이 무거워진 임산부부터, 아기를 들고 움직여야하는 출산 후까지 유용해요." },
    { id:"s2-05", name:"핸드워시", priority:"선택", target:"mom", emoji:"🧴", desc:"식약처 기준 만 3세 이하 어린이에게 사용금지인 보존제가 없는 제품으로 골라보아요." },
    { id:"s2-06", name:"욕실세정제", priority:"선택", target:"mom", emoji:"🚿", desc:"임신 중엔 독한 냄새가 더 부탁될 수 있어요. 강한 락스보다는 식물성 욕실세정제로 대체하세요." },
    { id:"s2-07", name:"식기세제 / 의류세제", priority:"선택", target:"mom", emoji:"🫧", desc:"아기용품을 미리 세탁할때도 사용하니, 순한 성분의 식기 세정제, 의류 세제로 바꾸는 좋은 기회예요." }
  ],
  s3: [
    { id:"s3-01", name:"젖병 / 젖꼭지", priority:"필수", target:"baby", emoji:"🍼", desc:"처음엔 작은 용량으로 시작하고, 분유량이 늘어나면 그 때부터 용량이 큰 젖병을 추가해도 괜찮아요." },
    { id:"s3-02", name:"젖병솔 / 젖꼭지솔", priority:"필수", target:"baby", emoji:"🧹", desc:"젖병 구석까지 닦을 수 있는 전용 솔이 편해요. 주기적으로 바꾸어주는 것이 좋지만, 브랜드별 차이는 크지 않아요." },
    { id:"s3-03", name:"젖병세정제", priority:"필수", target:"baby", emoji:"🫧", desc:"젖병을 깔끔하게 세정할 수 있도록 세척력이 좋고, 화학성분이 없는 제품을 고르세요." },
    { id:"s3-04", name:"젖병소독기", priority:"필수", target:"baby", emoji:"🔥", desc:"젖병을 자주 쓰는 시기에 소독 시간을 줄여줘요. 젖병 소독 외에도 장난감 등 소독에도 쓸 수 있어요." },
    { id:"s3-05", name:"배냇저고리 / 내의", priority:"필수", target:"baby", emoji:"👶", desc:"아기가 태어나서 처음 입는 옷이라 부드러운 소재가 좋아요! 병원, 조리원에서 제공해주기도 해요." },
    { id:"s3-06", name:"속싸개", priority:"필수", target:"baby", emoji:"🧣", desc:"부드러운 순면으로 흡수력 좋은 제품을 고르세요. 천기저귀로 대체하기도 해요!" },
    { id:"s3-07", name:"손싸개 / 발싸개 / 모자", priority:"필수", target:"baby", emoji:"🧤", desc:"아기가 체온을 유지하고, 얼굴을 긁어 상처를 입지 않도록 준비해요.너무 조이지 않는 제품이 좋아요." },
    { id:"s3-08", name:"유아올인원클렌저", priority:"필수", target:"baby", emoji:"🧴", desc:"신생아 피부는 예민할 수 있으니 순한 성분을 골라요. 100ml를 가지고도 정말 오래 쓸 수 있어요." },
    { id:"s3-09", name:"유아욕조", priority:"필수", target:"baby", emoji:"🛁", desc:"목욕 자세를 잡기 쉬워요. 아기가 미끄러지지 않도록 등을 받쳐주는 제품이 좋아요." },
    { id:"s3-10", name:"유아타올 / 천기저귀", priority:"필수", target:"baby", emoji:"🏖️", desc:"목욕 후 물기를 부드럽게 닦아줘요. 천기저귀나 속싸개로도 대체할 수 있어요." },
    { id:"s3-11", name:"체온계", priority:"필수", target:"baby", emoji:"🌡️", desc:"신생아는 열 체크가 중요해하니 미리 준비해요. 접촉식/비접촉식이 있습니다." },
    { id:"s3-12", name:"유아로션 / 크림 / 밤", priority:"필수", target:"baby", emoji:"✨", desc:"목욕 후 보습에 필요해요. 건조한 부위엔 크림이나 밤을 덧발라요. 올인원 제품이 일반적이지만, 따로 구매할 수도 있어요." },
    { id:"s3-13", name:"유아면봉 / 핀셋", priority:"필수", target:"baby", emoji:"🩹", desc:"간단한 오염 제거 및 탯줄 소독 등에 활용하지만, 다치지 않도록 주의하세요." },
    { id:"s3-14", name:"유아손톱깎이 / 가위", priority:"필수", target:"baby", emoji:"✂️", desc:"손톱이 빨리 자라 얼굴을 긁기 쉬우요. 끝이 둥근 제품으로 안전하게 자를 수 있어요." },
    { id:"s3-15", name:"아기침대", priority:"필수", target:"baby", emoji:"🛏️", desc:"안전 가드가 설치된 제품으로 아기를 안전하게 재우기 위해 필요해요. 매트리스와 가드가 흔들리지 않아야해요." },
    { id:"s3-16", name:"카시트", priority:"필수", target:"baby", emoji:"🚗", desc:"퇴원길부터 필요한 용품이에요. 도로교통법에 의거, 차량용 영유아 카시트 착용은 필수!" },
    { id:"s3-17", name:"아기띠", priority:"필수", target:"baby", emoji:"🎒", desc:"양손이 필요할때 유용해요. 신생아용 패드와 허리 지지감을 함께 살펴야해요." },
    { id:"s3-18", name:"유모차", priority:"필수", target:"baby", emoji:"🛒", desc:"크고 멋진 유모차도 좋지만, 엄마가 주로 사용할 예정이라면 휴대성도 중요해요." },
    { id:"s3-19", name:"세제", priority:"필수", target:"baby", emoji:"🧺", desc:"아기 옷은 자주 빨게 되니 자극이 적고 성분이 좋은 친환경 제품을 선택하세요." },
    { id:"s3-20", name:"가제 손수건", priority:"필수", target:"baby", emoji:"🧻", desc:"수유, 목욕, 침 닦기 등에 매일 사용해요. 넉넉히 50장이면 '얼른 빨래하자!'는 위기를 미리 대비할 수 있어요." },
    { id:"s3-21", name:"젖병소독집게", priority:"권장", target:"baby", emoji:"🥢", desc:"소독한 젖병을 손으로 만지지 않도록 집게를 준비하면 위생 관리가 편해져요." },
    { id:"s3-22", name:"분유포트", priority:"권장", target:"baby", emoji:"♨️", desc:"분요 물 온도를 맞추기 쉬워 밤중 수유가 편해져요. 세척 구조도 확인하세요." },
    { id:"s3-23", name:"겉싸개", priority:"권장", target:"baby", emoji:"🧥", desc:"쌀쌀한 계절에는 꼭 필요해요. 블랭킷 겸용으로 사용 가능한 제품이 실용적이에요." },
    { id:"s3-24", name:"바디슈트 / 우주복", priority:"권장", target:"baby", emoji:"👕", desc:"기저귀를 갈기 쉬운 디자인이 좋아요. 신생아부터 8개월까지 실내복이나 외출복으로 입히기 좋아요." },
    { id:"s3-25", name:"온습도계", priority:"권장", target:"baby", emoji:"💧", desc:"신생아는 실내 환경에 민감해요. 지속적인 실내 온/습도 체크로 아기 건강 관리에 유용해요." },
    { id:"s3-26", name:"콧물흡입기", priority:"권장", target:"baby", emoji:"👃", desc:"콧물, 코딱지로 아기가 숨쉬기 힘들 때 사용해요. 코가 막히면 수유와 잠이 힘들어저요." },
    { id:"s3-27", name:"모빌", priority:"권장", target:"baby", emoji:"🎠", desc:"100일까지는 흑백모빌을, 그 이후 컬러모빌을 사용해요. 단단히 고정될 수 있는 제품이 좋아요." },
    { id:"s3-28", name:"뒤집기 방지쿠션", priority:"권장", target:"baby", emoji:"🛡️", desc:"아기가 자다가 뒤집어 발생하는 사고를 예방해요. 너무 푹신한 제품은 피하는게 좋아요." },
    { id:"s3-29", name:"유아오일 / 젤", priority:"선택", target:"baby", emoji:"💆", desc:"오일로 아이를 마사지해주며 유대감을 키울 수 있어요. 향이 순한 제품으로 골라요." },
    { id:"s3-30", name:"태열베개", priority:"선택", target:"baby", emoji:"❄️", desc:"머리에 열이 많은 아기에게 도움이 돼요. 공기가 잘 통하는지, 세탁하기 편한지 확인해보세요." },
    { id:"s3-31", name:"역류방지쿠션", priority:"선택", target:"baby", emoji:"📐", desc:"수유 후 그대로 뱉어내거나 트림을 잘 하지 않는 아기에게 필요해요." },
    { id:"s3-32", name:"유아매트리스", priority:"선택", target:"baby", emoji:"🛋️", desc:"뒤집기방지 쿠션을 샀다면 별도로 구매하지 않아도 돼요. 너무 푹신한 제품은 피해주세요." },
    { id:"s3-33", name:"유모차시트", priority:"선택", target:"baby", emoji:"💺", desc:"아기 고객님의 편안한 탑승을 위하여 사용한답니다. 공기가 잘 통하는지 확인해봐요." },
    { id:"s3-34", name:"유모차블랭킷", priority:"선택", target:"baby", emoji:"🧶", desc:"아기의 체온유지는 어디서든 중요하니까요. 계절에 맞는 두께로 준비하면 좋아요." },
    { id:"s3-35", name:"유모차 커버", priority:"선택", target:"baby", emoji:"🌬️", desc:"외풍을 막아주는 보온기능과, 해충퇴치 효과가 있어요. 아기가 답답하지 않게 통풍이 잘되는 제품이 좋아요." },
    { id:"s3-36", name:"유모차햇빛가리개", priority:"선택", target:"baby", emoji:"🌞", desc:"햇빛이 강한 날 눈부심을 줄여줘요. 유모차와 잘 맞는지 먼저 확인해봐요." },
    { id:"s3-37", name:"슬링", priority:"선택", target:"baby", emoji:"🤱", desc:"눕혀서 한쪽 어깨로 안는 아기띠로, 아기 무게 15kg 내외까지만 사용해요." },
    { id:"s3-38", name:"천연소화제", priority:"선택", target:"mom", emoji:"💊", desc:"제산제는 속쓰림이 생기는 임신 후기에 유용해요." }
  ],
  s4: [
    { id:"s4-01", name:"분유", priority:"필수", target:"baby", emoji:"🍼", desc:"미리 대량 구매하기 보다, 조금씩 준비해 아이에게 맞는 것을 추가구매합니다." },
    { id:"s4-02", name:"기저귀", priority:"필수", target:"baby", emoji:"🧷", desc:"다양한 샘플을 사용해본 뒤 아기에게 맞는 것을 선택해도 늦지 않아요." },
    { id:"s4-03", name:"물티슈", priority:"필수", target:"baby", emoji:"🧻", desc:"기저귀 갈때 자주 사용해요. 피부에 직접 닿는 만큼 성분과 두께를 꼼꼼히 살펴보세요." },
    { id:"s4-04", name:"임산부 내의", priority:"필수", target:"mom", emoji:"👚", desc:"조리원에서 체온 조절이 필요할 수 있어요. 조이지 않는 내의를 챙기면 편해요." },
    { id:"s4-05", name:"미세모 칫솔 / 치약", priority:"필수", target:"mom", emoji:"🪥", desc:"미세 칫솔모를 사용하여 치주염을 예방해요. 출산가방에 소량 챙겨요." },
    { id:"s4-06", name:"산모 패드", priority:"필수", target:"mom", emoji:"🩹", desc:"출산 직후 나오는 오로 이후 양이 줄어들면 오버나이트로 대체하셔도 좋아요." },
    { id:"s4-07", name:"유두보호크림", priority:"필수", target:"mom", emoji:"🧴", desc:"유두균열이 생길 때 연고처럼 바를 수 있고, 아이 입에 닿아도 안전한 성분의 제품이 많아요." },
    { id:"s4-08", name:"유축기", priority:"필수", target:"mom", emoji:"🔌", desc:"유축 수유 계획이 있다면 유축기와 함께 모유저장팩, 세정제, 세척솔도 셋트로 필요해요!" },
    { id:"s4-09", name:"모유저장팩", priority:"필수", target:"mom", emoji:"🥡", desc:"모유 유축 후 저장팩에 보관하면 신선하게 보관할 수 있어요." },
    { id:"s4-10", name:"수유패드", priority:"필수", target:"mom", emoji:"💧", desc:"모유가 새는 시기에 옷을 보호해줘요. 외출 시 소량 들고다니는 것도 좋아요." },
    { id:"s4-11", name:"거즈손수건", priority:"필수", target:"baby", emoji:"🧻", desc:"아기뿐 아니라 엄마도 수유패드 대용으로 사용해요. 출산가방에는 10장이면 충분!" },
    { id:"s4-12", name:"섬유유연제", priority:"권장", target:"baby", emoji:"🌸", desc:"유아 의류의 정전기를 방지하고 옷감을 부드럽게 해주지만 필수는 아니예요." },
    { id:"s4-13", name:"복대 (산후)", priority:"권장", target:"mom", emoji:"🎗️", desc:"자궁 수축을 도와주고, 제왕 절개 시, 상처부위 지지 & 신체 회복 용도로 사용해요." },
    { id:"s4-14", name:"손목보호대", priority:"권장", target:"mom", emoji:"🤲", desc:"수유와 안기로 손목을 많이 쓰면서 약해진 관절을 지지해줘요. 너무 조이지 않게 사용해요." },
    { id:"s4-15", name:"잠옷 / 안대 / 마스크", priority:"권장", target:"mom", emoji:"😴", desc:"조리원 생활을 하다보면 없던 불면증도 생길 수 있어요. 조리원에서 원피스를 주기도 해요!" },
    { id:"s4-16", name:"유두보호기", priority:"권장", target:"mom", emoji:"🛡️", desc:"직수 연습 시, 아기가 유두를 더 잘 물 수 있도록 도와줘요.통증에도 도움이 될 수 있어요." },
    { id:"s4-17", name:"회음부방석", priority:"권장", target:"mom", emoji:"🪑", desc:"자연분만 시 회음부 통증으로 앉아있기 힘들 때 도움을 줘요. 너무 딱딱히지 않은 제품이 좋아요." },
    { id:"s4-18", name:"수면양말", priority:"권장", target:"mom", emoji:"🧦", desc:"출산 후 산후풍, 냉방병 등을 예방하고 체온 보호를 위해 필요해요." },
    { id:"s4-19", name:"세탁비누", priority:"선택", target:"baby", emoji:"🧼", desc:"작은 얼룩은 바로 손빨래하기 좋아요. 유아용 얼룩 제거 비누면 부담이 덜해요." },
    { id:"s4-20", name:"유아표백제", priority:"선택", target:"baby", emoji:"✨", desc:"하얀 옷감을 유지하려면 유아용 표백제나 얼룩 제거 비누가 있어요." },
    { id:"s4-21", name:"가슴마사지팩", priority:"선택", target:"mom", emoji:"🧊", desc:"찜질팩도 있고, 시트팩도 있어요. 바로 닿는 부분인만큼 소재까지 신경 써보아요." },
    { id:"s4-22", name:"회음부 약", priority:"선택", target:"mom", emoji:"💊", desc:"출산 전후로 회음부 통증이 느껴진다면 사용할 수 있어요." },
    { id:"s4-23", name:"튼살크림 / 핸드크림 / 립밤", priority:"선택", target:"mom", emoji:"💄", desc:"입원 중에도 피부가 건조할 수 있어요. 평소 쓰던 제품을 소분해 챙겨요." }
  ],
  s5: [
    { id:"s5-01", name:"수유쿠션", priority:"필수", target:"mombaby", emoji:"🤱", desc:"수유 자세를 잡기 쉽고 허리 부담을 줄여줘요. 모유·분유 수유 모두에 유용해요." },
    { id:"s5-02", name:"배변매트", priority:"필수", target:"baby", emoji:"🛏️", desc:"기저귀를 갈 때 아기를 안전하게 올려놓을 수 있어요. 방수 소재면 세탁이 편해요." },
    { id:"s5-03", name:"기저귀크림", priority:"필수", target:"baby", emoji:"🧴", desc:"기저귀 발진을 예방해요. 갈 때마다 얇게 발라주면 피부가 편안해져요." },
    { id:"s5-04", name:"기저귀통 / 휴지통", priority:"권장", target:"baby", emoji:"🗑️", desc:"냄새 차단 기능이 있으면 실내 공기 관리에 도움이 돼요. 봉투 교체가 쉬운지도 확인하세요." },
    { id:"s5-05", name:"아기모니터", priority:"권장", target:"baby", emoji:"📹", desc:"아기 방에서 울음·호흡을 확인할 수 있어요. 영상형과 소리만 전달하는 제품이 있어요." },
    { id:"s5-06", name:"백색소음기", priority:"권장", target:"baby", emoji:"🔊", desc:"태중 소리와 비슷한 백색소음이 수면에 도움이 될 수 있어요. 볼륨은 너무 크지 않게 사용해요." },
    { id:"s5-07", name:"가습기", priority:"권장", target:"baby", emoji:"💨", desc:"건조한 실내는 아기 코·피부에 불편할 수 있어요. 청소가 쉬운 제품을 고르세요." },
    { id:"s5-08", name:"수유등", priority:"권장", target:"mombaby", emoji:"💡", desc:"밤중 수유 시 눈부심을 줄여줘요. 밝기 조절이 되는 제품이 편해요." },
    { id:"s5-09", name:"젖병건조대", priority:"권장", target:"baby", emoji:"🧺", desc:"세척한 젖병을 위생적으로 말릴 수 있어요. 주방 공간에 맞는 크기를 골라요." },
    { id:"s5-10", name:"방수요 / 기저귀패드", priority:"필수", target:"baby", emoji:"💧", desc:"침대·소파 오염을 막아줘요. 아기침대 위에 깔아두면 세탁 부담이 줄어요." },
    { id:"s5-11", name:"스와들", priority:"권장", target:"baby", emoji:"🧣", desc:"생후 초기에 팔다리 움찔거림을 줄여 수면을 도와줘요. 너무 조이지 않게 사용해요." },
    { id:"s5-12", name:"탯줄관리용품", priority:"필수", target:"baby", emoji:"🩹", desc:"탯줄이 떨어질 때까지 위생적으로 관리해요. 알코올 솜이나 전용 스틱을 준비하세요." },
    { id:"s5-13", name:"아기이불", priority:"권장", target:"baby", emoji:"🛌", desc:"얇고 통기성 좋은 소재가 좋아요. 뒤집기 전에는 두꺼운 이불은 피하는 것이 안전해요." },
    { id:"s5-14", name:"목욕의자", priority:"권장", target:"baby", emoji:"🪑", desc:"혼자 목욕시키기 어려울 때 아기를 받쳐줘요. 미끄럼 방지가 되는지 확인하세요." },
    { id:"s5-15", name:"욕조받침대", priority:"선택", target:"baby", emoji:"🛁", desc:"욕조를 높여 허리 부담을 줄여줘요. 공간이 넉넉할 때 유용해요." },
    { id:"s5-16", name:"비듬빗", priority:"권장", target:"baby", emoji:"🪮", desc:"아기 두피에 생기는 비듬 관리에 사용해요. 부드럽게 빗어주세요." },
    { id:"s5-17", name:"아기빗", priority:"권장", target:"baby", emoji:"💇", desc:"머리카락이 자라기 시작하면 부드러운 빗으로 정리해요." },
    { id:"s5-18", name:"전기장판", priority:"선택", target:"mombaby", emoji:"🔥", desc:"겨울철 실내 온도 유지에 도움이 돼요. 아기와 함께 쓸 때는 저온 설정을 사용해요." },
    { id:"s5-19", name:"공기청정기", priority:"선택", target:"mombaby", emoji:"🌬️", desc:"미세먼지·실내 공기 정화에 도움이 돼요. 아기 방 크기에 맞는 용량을 고르세요." },
    { id:"s5-20", name:"분유보관통", priority:"권장", target:"baby", emoji:"🥛", desc:"외출 시 분유를 위생적으로 보관해요. 밀폐력과 휴대성을 확인하세요." },
    { id:"s5-21", name:"젖병보관함", priority:"권장", target:"baby", emoji:"📦", desc:"세척·소독한 젖병을 먼지 없이 보관해요. 통풍이 잘 되는 구조가 좋아요." },
    { id:"s5-22", name:"스피터업타월 / 턱받이", priority:"필수", target:"baby", emoji:"👕", desc:"수유 후 트림할 때나 침을 흘릴 때 사용해요. 흡수력 좋은 소재를 여러 장 준비하세요." },
    { id:"s5-23", name:"아기체중계", priority:"선택", target:"baby", emoji:"⚖️", desc:"수유량·성장 확인에 도움이 돼요. 영유아용 저울은 정밀도를 확인하세요." },
    { id:"s5-24", name:"젖병워머", priority:"권장", target:"baby", emoji:"♨️", desc:"분유·이유식 온도를 맞추기 편해요. 밤중 수유 시간을 줄여줄 수 있어요." },
    { id:"s5-25", name:"유아손톱 네일파일", priority:"권장", target:"baby", emoji:"💅", desc:"손톱깎이가 부담스러울 때 네일파일로 다듬을 수 있어요. 아기 전용 제품을 사용하세요." },
    { id:"s5-26", name:"무드등", priority:"선택", target:"baby", emoji:"🌙", desc:"은은한 조명이 밤중 수유·기저귀 교체에 도움이 돼요. 밝기·색온도 조절이 가능하면 좋아요." }
  ],
  s6: [
    { id:"s6-01", name:"이유식기", priority:"필수", target:"baby", emoji:"🥣", desc:"이유식 시작 시 그릇·용기가 필요해요. 넘어지지 않게 받침이 있는 제품이 좋아요." },
    { id:"s6-02", name:"이유식숟가락", priority:"필수", target:"baby", emoji:"🥄", desc:"실리콘 소재는 아기 입에 부담이 적어요. 열에 강한지 확인하세요." },
    { id:"s6-03", name:"치발기", priority:"필수", target:"baby", emoji:"🦷", desc:"잇몸이 가려울 때 씹어주면 진정에 도움이 돼요. 소재와 세척 방법을 확인하세요." },
    { id:"s6-04", name:"앉은뱅이쿠션", priority:"권장", target:"baby", emoji:"🪑", desc:"혼자 앉기 연습할 때 넘어짐을 방지해줘요. 너무 높지 않은 제품이 안전해요." },
    { id:"s6-05", name:"바운서", priority:"권장", target:"baby", emoji:"🪀", desc:"짧은 시간 동안 안전하게 눕혀둘 수 있어요. 항상 시야 안에 두고 사용하세요." },
    { id:"s6-06", name:"놀이매트", priority:"권장", target:"baby", emoji:"🧩", desc:"뒤집기·배밀이 연습에 넓은 공간이 필요해요. 쿠션감과 세척 편의성을 확인하세요." }
  ],
  s7: [
    { id:"s7-01", name:"하이체어", priority:"필수", target:"baby", emoji:"🪑", desc:"이유식·가족 식사 시 안전하게 앉힐 수 있어요. 발받침과 안전벨트를 확인하세요." },
    { id:"s7-02", name:"학습컵 / 빨대컵", priority:"필수", target:"baby", emoji:"🥤", desc:"컵으로 마시는 연습을 시작해요. 넘침 방지와 세척 편의성이 중요해요." },
    { id:"s7-03", name:"걸음마보조", priority:"권장", target:"baby", emoji:"🚶", desc:"뒤집기·기기 이후 서기·걷기 연습에 도움이 돼요. 속도 조절이 가능한지 확인하세요." },
    { id:"s7-04", name:"안전문", priority:"권장", target:"baby", emoji:"🚪", desc:"계단·위험 구역 출입을 막아줘요. 벽면·문틀에 맞는 설치 방식을 확인하세요." },
    { id:"s7-05", name:"모서리보호대", priority:"권장", target:"baby", emoji:"🛡️", desc:"가구 모서리 충돌을 방지해요. 접착력과 재부착 가능 여부를 확인하세요." },
    { id:"s7-06", name:"콘센트안전커버", priority:"권장", target:"baby", emoji:"🔌", desc:"전기 콘센트에 손가락이 들어가지 않도록 막아줘요. 아기가 뽑기 어려운 제품이 좋아요." },
    { id:"s7-07", name:"아기운동화", priority:"권장", target:"baby", emoji:"👟", desc:"걷기 시작하면 발에 맞는 신발이 필요해요. 미끄럼 방지 밑창을 확인하세요." },
    { id:"s7-08", name:"기저귀가방", priority:"권장", target:"mombaby", emoji:"👜", desc:"외출 시 기저귀·물티슈·옷을 한곳에 담아요. 어깨끈과 수납공간을 확인하세요." },
    { id:"s7-09", name:"촉감놀이감", priority:"권장", target:"baby", emoji:"🧸", desc:"다양한 촉감·소리로 감각 발달을 도와줘요. 작은 부품이 없는 안전한 제품을 고르세요." },
    { id:"s7-10", name:"아기칫솔 / 치약", priority:"권장", target:"baby", emoji:"🪥", desc:"이가 나기 시작하면 칫솔질을 시작해요. 불소 없는 유아용 치약을 사용하세요." }
  ],
  s8: [
    { id:"s8-01", name:"유아용 카시트", priority:"권장", target:"baby", emoji:"🚗", desc:"체중·키에 맞게 전환형 카시트로 바꿀 시기예요. 설치 방법을 미리 익혀두세요." },
    { id:"s8-02", name:"전동차 / 푸시카", priority:"선택", target:"baby", emoji:"🚙", desc:"돌 전후 균형감각·하체 힘 기르기에 도움이 돼요. 안전벨트와 속도를 확인하세요." },
    { id:"s8-03", name:"보드북 / 그림책", priority:"권장", target:"baby", emoji:"📖", desc:"두꺼운 페이지로 찢어지지 않아요. 함께 읽으며 언어·집중력 발달에 도움이 돼요." },
    { id:"s8-04", name:"실내화 / 슬리퍼", priority:"권장", target:"baby", emoji:"🥿", desc:"실내에서 미끄럼 방지 밑창이 있는 신발이 좋아요. 발가락이 편한지 확인하세요." },
    { id:"s8-05", name:"유아식기세트", priority:"권장", target:"baby", emoji:"🍽️", desc:"스스로 먹기 연습에 맞는 그릇·숟가락·포크 세트예요. 열에 강하고 넘어지지 않는 제품이 좋아요." },
    { id:"s8-06", name:"낮잠침대 / 유아침대", priority:"선택", target:"baby", emoji:"🛏️", desc:"낮잠·독립 수면 공간이 필요할 때 유용해요. 낙상 방지 가드가 있는지 확인하세요." },
    { id:"s8-07", name:"유아복 (90~100)", priority:"권장", target:"baby", emoji:"👕", desc:"활동량이 늘어나면 편한 실내복·외출복이 필요해요. 여유 있는 사이즈를 고르세요." }
  ]
};
